const PRODUCTS=[
{name:"Nike Zoom Rival Sprint Glam",brand:"NIKE",cat:"Sprint",price:66.49,old:94.99,discount:"-30%",url:"https://www.nike.com/fr/t/chaussure-a-pointes-de-sprint-nike-zoom-rival-sprint-glam-e5PpDV1p",img:"https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto%2Cu_9ddf04c7-2a9a-4d76-add1-d15af8f0263d%2Cc_scale%2Cfl_relative%2Cw_1.0%2Ch_1.0%2Cfl_layer_apply/ec4b5d29-15ce-41e4-82fb-7e61950a6d59/ZOOM%2BRIVAL%2BSPRINT.png"},
{name:"Adizero Sprintstar",brand:"ADIDAS",cat:"Sprint",price:56,old:80,discount:"-30%",url:"https://www.adidas.fr/athletisme-a_pointes",img:"https://assets.adidas.com/images/w_500%2Cf_auto%2Cq_auto/40ee3c74f22c40a997ab29e48fb5964c_9366/Chaussure_Adizero_Sprintstar_Blanc_KI8378_01_00_standard.jpg"},
{name:"Adizero Prime SP 4",brand:"ADIDAS",cat:"Sprint",price:100,old:200,discount:"-50%",url:"https://www.adidas.fr/athletisme-a_pointes",img:"https://assets.adidas.com/images/w_500%2Cf_auto%2Cq_auto/6d66e24ca2aa48c8ad6f686ea5899636_9366/Chaussure_Adizero_Prime_SP_4_Rose_KJ7097_01_00_standard.jpg"},
{name:"Adizero Finesse",brand:"ADIDAS",cat:"Sprint",price:128,old:160,discount:"-20%",url:"https://www.adidas.fr/chaussure-adizero-finesse/JQ5931.html",img:"https://assets.adidas.com/images/w_500%2Cf_auto%2Cq_auto/2ac2acbaba8449feaae05838ef92b082_9366/Chaussure_ADIZERO_FINESSE_Vert_JQ5931_01_00_standard.jpg"},
{name:"Adizero Avanti",brand:"ADIDAS",cat:"Demi-fond",price:126,old:180,discount:"-30%",url:"https://www.adidas.fr/athletisme-a_pointes",img:"https://assets.adidas.com/images/w_500%2Cf_auto%2Cq_auto/8d2dd6fd9f064f1ab770ef2bd5b9f8ea_9366/Chaussure_Adizero_Avanti_Performance_Noir_JQ8938_01_00_standard.jpg"},
{name:"evoSPEED Sprint 14.5",brand:"PUMA",cat:"Sprint",price:63,old:90,discount:"-30%",url:"https://eu.puma.com/fr/fr/pd/chaussures-de-running-evospeed-sprint14-5/311872",img:"https://images.puma.com/image/upload/f_auto%2Cq_auto%2Cb_rgb%3Afafafa%2Cw_100%2Ch_100/global/311872/01/sv01/fnd/EEA/fmt/png/Chaussures-de-running-evoSPEED-Sprint14.5"},
{name:"Adizero TJ/PV",brand:"ADIDAS",cat:"Saut",price:97.5,old:105,discount:"-7%",url:"https://www.adidas.fr/athletisme-a_pointes",img:"https://assets.adidas.com/images/w_500%2Cf_auto%2Cq_auto/5a7e7b4f5c6f4a6aa01ce985ed8a3b31_9366/Chaussure_Adizero_TJ_PV_Performance_Blanc_JQ6173_01_00_standard.jpg"},
{name:"Adizero Javelin",brand:"ADIDAS",cat:"Lancer",price:112,old:160,discount:"-30%",url:"https://www.adidas.fr/athletisme-a_pointes",img:"https://assets.adidas.com/images/w_500%2Cf_auto%2Cq_auto/5f1ffb6c7fb64b7bbcb5a1545442f458_9366/Chaussure_de_lancer_de_javelot_Adizero_Bleu_JQ6200_01_00_standard.jpg"}
];
let state={cat:"Tous",query:"",cart:[]};
const grid=document.getElementById("grid"),search=document.getElementById("search"),cart=document.getElementById("cart"),overlay=document.getElementById("overlay"),items=document.getElementById("items"),count=document.getElementById("count"),total=document.getElementById("total"),toast=document.getElementById("toast");
const money=n=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(n);
function render(){const list=PRODUCTS.filter(p=>(state.cat==="Tous"||p.cat===state.cat)&&p.name.toLowerCase().includes(state.query.toLowerCase()));grid.innerHTML=list.map((p,i)=>'<article class="card"><div class="photo"><span class="promo">'+p.discount+'</span><img src="'+p.img+'" alt="'+p.name+'"></div><div class="card-info"><div class="brand-name">'+p.brand+' · ATHLÉTISME</div><h3>'+p.name+'</h3><div class="pricing"><span class="old">'+money(p.old)+'</span><span class="new">'+money(p.price)+'</span></div><div class="card-actions"><button class="add" data-add="'+PRODUCTS.indexOf(p)+'">Ajouter</button><a class="view" href="'+p.url+'" target="_blank" rel="noopener">Fiche ↗</a></div></div></article>').join("")||'<p class="muted">Aucun produit trouvé.</p>'}
function cartRender(){count.textContent=state.cart.length;items.innerHTML=state.cart.length?state.cart.map((p,i)=>'<div class="line"><div><h4>'+p.name+'</h4><small>'+money(p.price)+'</small></div><button class="remove" data-remove="'+i+'">✕</button></div>').join(""):'<div class="empty">Ton panier est vide.</div>';total.textContent=money(state.cart.reduce((s,p)=>s+p.price,0))}
function openCart(){cart.classList.add("open");overlay.classList.remove("hidden");cart.setAttribute("aria-hidden","false")}
function closeCart(){cart.classList.remove("open");overlay.classList.add("hidden");cart.setAttribute("aria-hidden","true")}
function say(t){toast.textContent=t;toast.classList.add("show");clearTimeout(window.t);window.t=setTimeout(()=>toast.classList.remove("show"),1500)}
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.cat=b.dataset.cat;render()}));
document.querySelectorAll("[data-cat2]").forEach(b=>b.addEventListener("click",()=>{state.cat=b.dataset.cat2;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x.dataset.cat===state.cat));render();document.getElementById("products").scrollIntoView({behavior:"smooth"})}));
search.addEventListener("input",e=>{state.query=e.target.value;render()});
grid.addEventListener("click",e=>{const b=e.target.closest("[data-add]");if(!b)return;state.cart.push(PRODUCTS[+b.dataset.add]);cartRender();say("Produit ajouté ✓")});
items.addEventListener("click",e=>{const b=e.target.closest("[data-remove]");if(!b)return;state.cart.splice(+b.dataset.remove,1);cartRender()});
document.getElementById("cartOpen").addEventListener("click",openCart);document.getElementById("cartClose").addEventListener("click",closeCart);overlay.addEventListener("click",closeCart);
document.getElementById("empty").addEventListener("click",()=>{state.cart=[];cartRender()});
document.getElementById("pay").addEventListener("click",()=>{if(!state.cart.length){say("Ajoute un produit d’abord");return}say("Le paiement doit encore être relié à un compte de paiement");});
render();cartRender();
// T-shirts running présentés sur les pages promos officielles des marques.
